# Quad-wavelength emitter overlay for WDM stress
channels: 16
wavelength_nm: 1550.0
wavelengths_nm:
  - 1548.8
  - 1549.6
  - 1550.4
  - 1551.2
power_mw_per_ch: 7.0
extinction_db: 9.5
rin_dbhz: -118.0
modulation_mode: intensity
pushpull_alpha: 0.0
rise_fall_ns_10_90: 12.0
temp_coeff_pct_per_C: 0.35
