# High-power low-RIN emitter for Path B sweeps
wavelength_nm: 1550.0
power_mw_per_ch: 18.0
extinction_db: 20.0
rin_dbhz: -150.0
linewidth_hz: 5.0e6
rise_fall_ns_10_90: 6.0
temp_coeff_pct_per_C: 0.15
power_sigma_pct: 2.0
modulation_mode: pushpull
pushpull_alpha: 0.9
