channels: 8
wavelength_nm: 1550.0
power_mw_per_ch: 25.0
extinction_db: 25.0
rin_dbhz: -160.0
linewidth_hz: 1.0e6
rise_fall_ns_10_90: 4.0
temp_coeff_pct_per_C: 0.1
power_sigma_pct: 1.0
modulation_mode: pushpull
pushpull_alpha: 0.95

