channels: 1
wavelength_nm: 1550.0
power_mw_per_ch: 18.0
extinction_db: 20.0
rin_dbhz: -150.0
linewidth_hz: 1000000.0
wav_drift_nm_per_C: 0.05
rise_fall_ns_10_90: 3.0
temp_coeff_pct_per_C: 0.05
power_sigma_pct: 0.5
modulation_mode: pushpull
pushpull_alpha: 0.98
