ct_model: neighbor
ct_neighbor_db: -55.0
ct_diag_db: -58.0
transmittance: 0.9
psf_kernel: "lorentzian:w=1.5"
signal_scale: 1.35
w_plus_contrast: 0.92
w_minus_contrast: 0.92
stray_floor_db: -44.0
amp_on: true
amp_gain_db: 6.0
amp_ase_sigma: 0.006
sat_abs_on: true
sat_I_sat: 1.4
sat_alpha: 0.65



