ct_model: neighbor
ct_neighbor_db: -40.0
ct_diag_db: -45.0
psf_kernel: "lorentzian:w=3.0"
stray_floor_db: -38.0
transmittance: 0.8
tile_border_px: 1
tile_gain_sigma_pct: 1.0
tile_isolation: false
speckle_on: false


