ct_model: neighbor
ct_neighbor_db: -72.0
ct_diag_db: -76.0
psf_kernel: "lorentzian:w=1.6"
stray_floor_db: -52.0
transmittance: 0.94
signal_scale: 1.50
tile_border_px: 10
tile_gain_sigma_pct: 0.4
tile_isolation: true
grid_px: 320
speckle_on: false


