ct_model: neighbor
ct_neighbor_db: -55.0
ct_diag_db: -58.0
transmittance: 0.9
psf_kernel: "lorentzian:w=1.5"
signal_scale: 1.40
w_plus_contrast: 0.92
w_minus_contrast: 0.92
stray_floor_db: -44.0
amp_on: true
amp_gain_db: 8.0
amp_ase_sigma: 0.006


