channels: 1
transmittance: 0.95
ct_model: global
crosstalk_db: -80.0
signal_scale: 2.5
w_plus_contrast: 0.99
w_minus_contrast: 0.99
stray_floor_db: -80.0
amp_on: false
sat_abs_on: true
sat_I_sat: 0.25
sat_alpha: 0.95
soa_on: true
soa_small_signal_gain_db: 20.0
soa_psat_mw: 2.0
soa_noise_figure_db: 4.5
soa_tau_ns: 0.5
soa_alpha: 4.0
soa_pattern_alpha: 0.02
mzi_on: true
mzi_gain: 3.0
mzi_sat_mw: 1.5
mzi_hysteresis_mw: 0.05
mzi_bias_step: 0.05
mzi_bias_leak: 0.003
mzi_bias_target_mw: 0.0
servo_on: true
servo_kp: 0.1
servo_ki: 0.001
servo_alpha: 0.15
servo_ref_mw: 0.0
servo_leak: 0.01
servo_max_bias_mw: 2.0
voa_bits: 10
mode_mix_matrix: null
