ct_model: neighbor
ct_neighbor_db: -48.0
ct_diag_db: -52.0
psf_kernel: "lorentzian:w=2.5"
stray_floor_db: -42.0
transmittance: 0.85
tile_border_px: 2
tile_gain_sigma_pct: 0.7
tile_isolation: false
speckle_on: false


