channels: 8
transmittance: 0.92
ct_model: neighbor
ct_neighbor_db: -65.0
ct_diag_db: -68.0
psf_kernel: "lorentzian:w=0.6"
signal_scale: 2.8
w_plus_contrast: 0.99
w_minus_contrast: 0.99
stray_floor_db: -80.0
amp_on: false
sat_abs_on: true
sat_I_sat: 0.12
sat_alpha: 1.2
soa_on: true
soa_small_signal_gain_db: 24.0
soa_psat_mw: 2.0
soa_noise_figure_db: 4.5
soa_tau_ns: 0.5
soa_alpha: 4.0
soa_pattern_alpha: 0.02
mzi_on: true
mzi_gain: 3.5
mzi_sat_mw: 1.2
mzi_hysteresis_mw: 0.06
mzi_bias_step: 0.06
mzi_bias_leak: 0.004
mzi_bias_target_mw: 0.0
servo_on: true
servo_kp: 0.12
servo_ki: 0.002
servo_alpha: 0.12
servo_ref_mw: 0.0
servo_leak: 0.01
servo_max_bias_mw: 2.5
hard_clip_on: true
hard_clip_sat_mw: 0.06
post_clip_on: true
post_clip_sat_mw: 0.04
voa_bits: 10
mode_mix_matrix: null
