channels: 8
transmittance: 0.95
ct_model: neighbor
ct_neighbor_db: -60.0
ct_diag_db: -63.0
psf_kernel: "lorentzian:w=1.0"
signal_scale: 1.0
w_plus_contrast: 0.98
w_minus_contrast: 0.98
stray_floor_db: -75.0
amp_on: false
sat_abs_on: false
soa_on: true
soa_small_signal_gain_db: 16.0
soa_psat_mw: 8.0
soa_noise_figure_db: 5.0
soa_tau_ns: 0.6
soa_alpha: 4.0
soa_pattern_alpha: 0.05
mzi_on: true
mzi_gain: 2.0
mzi_sat_mw: 3.0
mzi_hysteresis_mw: 0.02
mzi_bias_step: 0.02
mzi_bias_leak: 0.002
mzi_bias_target_mw: 0.0
voa_bits: 9
mode_mix_matrix: null

servo_on: true
servo_kp: 0.02
servo_ki: 0.0005
servo_ref_mw: 0.0
servo_leak: 0.01
servo_max_bias_mw: 3.5
