ct_model: neighbor
ct_neighbor_db: -54.0
ct_diag_db: -57.0
transmittance: 0.92
psf_kernel: "lorentzian:w=1.5"
# Effective knobs used by the simulator
signal_scale: 1.60
w_plus_contrast: 0.92
w_minus_contrast: 0.92
stray_floor_db: -44.0


