ct_model: neighbor
ct_neighbor_db: -66.0
ct_diag_db: -70.0
psf_kernel: "lorentzian:w=1.8"
stray_floor_db: -50.0
transmittance: 0.94
signal_scale: 1.35
tile_border_px: 6
tile_gain_sigma_pct: 0.3
tile_isolation: true
speckle_on: false
grid_px: 256


