# Tuned TIA overlay for ~0.065 BER Path A recipe
# Derived from successful runs around 16–18 ns with OPA857EVM + BPW34
tia_transimpedance_kohm: 10.0
bw_mhz: 75.0
in_noise_pA_rthz: 6.1
peaking_q: 0.7
slew_v_per_us: 500.0
adc_bits: 10
adc_fullscale_v: 1.0
adc_read_noise_mV_rms: 0.0
gain_sigma_pct: 1.0

