name: pd_only
channels: 4
trials: 5
emitter_pack: configs/packs/emitter_typ.yaml
optics_pack: configs/packs/optics_typ.yaml
sensor_pack: configs/packs/sensor_typ.yaml
tia_pack: configs/packs/tia_typ.yaml
comparator_pack: configs/packs/comparator_typ.yaml
clock_pack: configs/packs/clock_typ.yaml
