transmittance: 0.7
w_plus_contrast: 0.85
w_minus_contrast: 0.84
crosstalk_db: -28.0
stray_floor_db: -38.0
psf_kernel: "lorentzian:w=2.5"
signal_scale: 1.0
amp_on: false
amp_gain_db: 10.0
sat_abs_on: false
sat_I_sat: 1.0
sat_alpha: 0.6
