transmittance: 0.6
w_plus_contrast: 0.8
w_minus_contrast: 0.78
crosstalk_db: -22.0
stray_floor_db: -32.0
psf_kernel: "lorentzian:w=3.0"
signal_scale: 1.0
amp_on: false
amp_gain_db: 12.0
sat_abs_on: false
sat_I_sat: 1.0
sat_alpha: 0.6
