ct_model: neighbor
crosstalk_db: -30.0
ct_neighbor_db: -30.0
ct_diag_db: -33.0
stray_floor_db: -75.0
transmittance: 0.72
amp_on: true
amp_gain_db: 2.0
amp_ase_sigma: 0.03
sat_abs_on: true
sat_I_sat: 0.6
sat_alpha: 1.2
voa_post_db: 2.0
soa_small_signal_gain_db: 3.0
soa_tau_ns: 20.0
soa_psat_mw: 20.0
