ct_model: neighbor
crosstalk_db: -22.0
stray_floor_db: -70.0
psf_kernel: none
transmittance: 0.6
ins_loss_db: 3.0
ins_loss_db_mean: 0.5
ins_loss_db_sigma: 0.7
pdl_db: 0.7
pdl_step_rad: 0.1
dwdm_slope_db_per_nm: 2.0
gdr_ps_pkpk: 15.0
reflection_event_db: 25.0
reflection_prob: 0.12
grid_px: 0
ct_neighbor_db: -22.0
ct_diag_db: -25.0
dwdm_passband_ripple_db: 1.5
speckle_time_on: true
speckle_time_sigma: 0.2
speckle_time_tau_frames: 20
xgm_on: true
xgm_coeff: 0.3
xpm_on: true
xpm_coeff: 0.2
fwm_on: true
fwm_coeff: 0.12
pol_scrambler_on: true
pol_scramble_every_frames: 10
amp_on: true
amp_gain_db: 3.0
amp_ase_sigma: 0.05
sat_abs_on: true
sat_I_sat: 0.7
sat_alpha: 0.95
