ct_model: neighbor
crosstalk_db: -30.0
ct_neighbor_db: -45.0
ct_diag_db: -48.0
transmittance: 0.80
psf_kernel: "lorentzian:w=2.0"
stray_floor_db: -70.0
ins_loss_db: 3.0
ins_loss_db_mean: 0.5
ins_loss_db_sigma: 0.5
pdl_db: 0.4
pdl_step_rad: 0.05
dwdm_slope_db_per_nm: 2.0
gdr_ps_pkpk: 15.0
reflection_event_db: 28.0
reflection_prob: 0.08
speckle_time_on: true
speckle_time_sigma: 0.1
speckle_time_tau_frames: 12
amp_on: true
amp_gain_db: 2.0
amp_ase_sigma: 0.03
sat_abs_on: true
sat_I_sat: 0.9
sat_alpha: 0.9
