transmittance: 0.6
ct_model: neighbor
ct_neighbor_db: -26.0
ct_diag_db: -30.0
stray_floor_db: -55.0
ins_loss_db_mean: 1.2
ins_loss_db_sigma: 0.6
pdl_db: 0.5
pdl_step_rad: 0.07
reflection_event_db: 30.0
reflection_prob: 0.1
speckle_time_on: true
speckle_time_sigma: 0.12
speckle_time_tau_frames: 15
