# Budget InGaAs/PIN sensor with higher noise and lower responsivity
responsivity_A_per_W: 0.65
dark_current_nA: 1.8
capacitance_pf: 1.2
bw_mhz: 45.0
shot_noise_scale: 1.0
thermal_noise_scale: 1.3
read_noise_e_rms: 1200
full_well_e: 12000
temp_coeff_pct_per_C: 0.4
notes: Derived from low-cost 8-ch InGaAs array module, room-temp
