# LED array style emitter pack: broader spectrum, higher RIN, slower drive
wavelength_nm: 1550.0
power_mw_per_ch: 6.0
extinction_db: 8.0
rin_dbhz: -120.0
linewidth_hz: 5.0e9
rise_fall_ns_10_90: 15.0
temp_coeff_pct_per_C: 0.4
power_sigma_pct: 6.0
modulation_mode: intensity
pushpull_alpha: 0.0
coherence_length_m: 0.02
notes: Modeled after budget InGaAs LED bar with integrated driver
