ct_model: neighbor
crosstalk_db: -40.0
stray_floor_db: -80.0
psf_kernel: none
transmittance: 0.72
amp_on: true
amp_gain_db: 2.0
amp_ase_sigma: 0.02
sat_abs_on: true
sat_I_sat: 0.5
sat_alpha: 1.2
voa_post_db: 2.0
soa_small_signal_gain_db: 3.0
soa_tau_ns: 20.0
soa_psat_mw: 20.0
