ct_model: neighbor
crosstalk_db: -30.0
stray_floor_db: -70.0
psf_kernel: none
transmittance: 0.72
ins_loss_db_mean: 0.5
ins_loss_db_sigma: 0.5
pdl_db: 0.4
pdl_step_rad: 0.05
dwdm_slope_db_per_nm: 2.0
gdr_ps_pkpk: 15.0
reflection_event_db: 28.0
reflection_prob: 0.08
grid_px: 0
ct_neighbor_db: -30.0
ct_diag_db: -33.0
speckle_time_on: true
speckle_time_sigma: 0.1
speckle_time_tau_frames: 12

# EDFA-oriented settings
amp_on: true
amp_type: edfa
soa_small_signal_gain_db: 6.0   # maps to EDFA small-signal gain in sim
soa_noise_figure_db: 5.0
obpf_bw_nm: 0.5

# Activation shaping to restore contraction
sat_abs_on: true
sat_I_sat: 0.7
sat_alpha: 1.2
post_clip_on: true
post_clip_sat_mw: 0.1
voa_post_db: 4.0

