# LED array stressed: lower power, higher RIN, worse stability
wavelength_nm: 1550.0
power_mw_per_ch: 4.0
extinction_db: 6.0
rin_dbhz: -110.0
linewidth_hz: 1.0e10
rise_fall_ns_10_90: 20.0
temp_coeff_pct_per_C: 0.6
power_sigma_pct: 8.0
modulation_mode: intensity
pushpull_alpha: 0.0
coherence_length_m: 0.01
notes: Stress test for bargain-bin LED tile
